### ISSUE TITLE
Update dependency (Quick)

### ISSUE THREAD

**Issue by gitMartynas** [auth0/SimpleKeychain#107]
Trying to add latest versions of Quick & Nimble frameworks into my project via SPM. But getting following error:

Dependencies could not be resolved because root depends on 'Quick' 4.0.0..<5.0.0 and root depends on 'SimpleKeychain' 0.12.2..<1.0.0.
'SimpleKeychain' >= 0.12.2 practically depends on 'Quick' 3.0.0..<4.0.0 because 'SimpleKeychain' 0.12.2 depends on 'Quick' 3.0.0..<4.0.0 and no versions of 'SimpleKeychain' match the requirement 0.12.3..<1.0.0.

Could you please update SimpleKeychain to use latest Quick & Nimble versions?

Also I was wondering if it is worth having these dependencies (Quick & Nimble) in such a small framework like SimpleKeychain. It contains only 20± unit tests. Please consider rewriting them using XCTest. Framework will become lighter and you will lose additional 3rd party dependencies.

**Comment by Widcket** [comment]
Hi @gitMartynas, thanks for raising this. I just tried adding a name to the test dependencies [so they don't get resolved](https://github.com/apple/swift-evolution/blob/master/proposals/0226-package-manager-target-based-dep-resolution.md), and that seems to solve the conflict.

<img width="690" alt="Screen Shot 2021-06-02 at 19 39 18" src="https://user-images.githubusercontent.com/5055789/120561223-836a4a00-c3da-11eb-901e-eb42bf96169f.png">

Can you please try the `test/spm-deps` branch to see if that solves your problem? If so, I'll make a PR and then a new release.

**Comment by gitMartynas** [comment]
Thanks, looks like issue is resolved now, but another appeared. Should I create issue on Auth0 git repo? :)

Dependencies could not be resolved because root depends on 'Quick' 4.0.0..<5.0.0.
'Quick' 3.0.0..<4.0.0 is required because 'Auth0.swift' depends on 'Quick' 3.0.0..<4.0.0 and root depends on 'Auth0.swift' 1.30.1..<2.0.0.

**Comment by Widcket** [comment]
No need to, I'll create the respective PRs and releases. Note that [JWTDecode.swift](https://github.com/auth0/JWTDecode.swift) needs to get the change first, as it's a dependency of Auth0.swift.

**Comment by Widcket** [comment]
@gitMartynas this should be solved with Auth0.swift [1.33.1](https://github.com/auth0/Auth0.swift/releases/tag/1.33.1).
