### ISSUE TITLE
Code Errors in Your README.

### ISSUE THREAD

**Issue by AndyIbanez** [auth0/SimpleKeychain#11]
You should update this project's README to fix the typos when documenting code.

Particularly when you are talking about using Touch ID, the code provided has errors:

`keychain.useAcessControl = true
keychain.defaultAccesiblity = .WhenPasscodeSetThisDeviceOnly`

They should be:

`keychain.useAccessControl = true
 keychain.defaultAccessiblity = .WhenPasscodeSetThisDeviceOnly`

The differences are subtle but naturally they don't allow the code to compile. Please update the snippet I mentioned with the one I just gave you. Thanks!

**Comment by woloski** [comment]
thx! pull request it! :smiley:

**Comment by AndyIbanez** [comment]
I have sent the pull request. Up to you to update now :)

**Comment by AndyIbanez** [comment]
I should mention that the property name `defaultAccessiblity` itself has a typo as well (should be `defaultAccessibility`, but that's a cosmetic change that I will tackle some other time (Y).
