### ISSUE TITLE
Next SimpleKeychain major release

### ISSUE THREAD

**Issue by Widcket** [auth0/SimpleKeychain#157]
Hello! 👋 

Today we published the SimpleKeychain 1.0.0 [First Availability release](https://github.com/auth0/SimpleKeychain/releases/tag/1.0.0-fa).

**The GA release is planned for the third week of July.**

### Highlights

- Improved error handling.
- Support for custom attributes.
- Support for sharing items with other devices through iCloud synchronization.

### Documentation

- [README](https://github.com/auth0/SimpleKeychain/tree/fa#readme)
- [Migration Guide](https://github.com/auth0/SimpleKeychain/blob/fa/V1_MIGRATION_GUIDE.md)
- [Changelog](https://github.com/auth0/SimpleKeychain/blob/fa/CHANGELOG.md)
- [API documentation](https://auth0.github.io/SimpleKeychain/documentation/simplekeychain/)

### Feedback

We’d love for you to give the FA release a try, and welcome your feedback on any recommendations or issues you encounter. Should you have any feedback or questions, please [raise an issue](https://github.com/auth0/SimpleKeychain/issues/new/choose).

**Comment by evansims** [comment]
🤖 Commenting to filter for internal tooling. Please disregard.

**Comment by Widcket** [comment]
The v1 release is out now! https://github.com/auth0/SimpleKeychain/releases/tag/1.0.0
