### ISSUE TITLE
@objc Annotations for Cross-Language usage

### ISSUE THREAD

**Issue by braandl** [auth0/SimpleKeychain#169]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/SimpleKeychain#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/SimpleKeychain/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/ios) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The public accessors of the new Version (1.0) do not use the `@objc` modifier, thus they can not be used in legacy  / objective-c code, which is sad and kind of unnecessary.

### Describe the ideal solution

Add `@objc` to public method signatures

**Comment by Widcket** [comment]
Hi @braandl, thanks for raising this.
As mentioned in the [migration guide](https://github.com/auth0/SimpleKeychain/blob/master/V1_MIGRATION_GUIDE.md#objective-c), SimpleKeychain no longer supports Objective-C.
So this is not something we'll be adding.

**Comment by braandl** [comment]
but why? isn't this totally unnecessary and a two minutes fix, simply forcing people like me to fork it?

**Comment by Widcket** [comment]
We're moving away from Objective-C in all our libraries.

> two minutes fix
SimpleKeychain is a struct, so it's not possible to simply add `@objc`. That can only be added to classes that inherit from `NSObject`. As an alternative to forking, you could wrap it using a class with `@objc` members, like this: https://github.com/auth0/Auth0.swift/blob/1.39.1/Auth0/_ObjectiveWebAuth.swift
