### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by sashabaranov** [auth0/SimpleKeychain#197]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/SimpleKeychain#readme) and the [Examples](https://github.com/auth0/SimpleKeychain/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/SimpleKeychain/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library?

### Describe the ideal solution

The library would have a privacy manifest 

### Additional context

https://github.com/auth0/Auth0.swift/issues/810

**Comment by iOSNinja** [comment]
Any update as to when the library would be updated with privacy manifest file & signature?

Thank you.
