### ISSUE TITLE
Add Privacy Manifest File

### ISSUE THREAD

**Issue by RizITN10** [auth0/SimpleKeychain#207]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/SimpleKeychain#readme) and the [Examples](https://github.com/auth0/SimpleKeychain/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/SimpleKeychain/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

Although Pushwoosh SDK isn't mentioned in Apple's provided list of SDKs (see link below), considering Apple's strict privacy policies, you should add the Privacy Manifest file on your own before it comes into their notice. Lots of the SDKs (Firebase, Facebook, Alamofire, etc.) have already updated their SDKs and added the required privacy manifest file.

[https://developer.apple.com/news/?id=r1henawx](https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/url)
[https://developer.apple.com/support/third-party-SDK-requirements/](https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/url)

### Describe the ideal solution

Add Privacy Manifest File

**Comment by Widcket** [comment]
Hi @RizITN10, please see https://github.com/auth0/SimpleKeychain/issues/206
