### ISSUE TITLE
Always getting "Error trying to access to non available kSecUseOperationPrompt in iOS7" log

### ISSUE THREAD

**Issue by adriana-elizondo** [auth0/SimpleKeychain#24]
I'm trying to use this on ios 7 and 8, so if I'm not using user access control and kSecUseOperationPrompt  either, but I'm always getting this error log in the query. 
Shouldnt it be like this? :

- (NSDictionary *)queryFetchOneByKey:(NSString *)key message:(NSString *)message {
    NSMutableDictionary *query = [self baseQuery];
    [query addEntriesFromDictionary:@{
                                      (__bridge id)kSecReturnData: @YES,
                                      (__bridge id)kSecMatchLimit: (__bridge id)kSecMatchLimitOne,
                                      (__bridge id)kSecAttrAccount: key,
                                      }];
#if TARGET_OS_IPHONE
    if (message) {
        if (self.useAccessControl && floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_7_1) {
            query[(__bridge id)kSecUseOperationPrompt] = message;
        } else {
            NSLog(@"Error trying to access to non available kSecUseOperationPrompt in iOS7");
        }
    }
#endif
    
    return query;
}

**Comment by RebornSoul** [comment]
Already discussed here https://github.com/auth0/SimpleKeychain/commit/71784e3099efbcf598bf80edf1f9915544c98663#commitcomment-14692321
This is not an error, but log is confusing. I suggest it should be removed.

**Comment by adriana-elizondo** [comment]
Sorry didn't see it, Thanks!
