### ISSUE TITLE
Keychain values stay after deleting the app

### ISSUE THREAD

**Issue by nico75005** [auth0/SimpleKeychain#28]
When I login with Auth0, I save the profile and the id_token using A0SimpleKeychain. Is it normal that once I delete the app and reinstall it, the keychain is still there? If it's normal, it's only available from my app right?

Thanks

**Comment by mruvim** [comment]
Keychain items are stored not in your app container therefore deleting the app does not effect them, and yes your keychain items are available only to your app. `Keychain rights depend on the provisioning profile used to sign your application`

For more info check [apple doc](https://developer.apple.com/library/mac/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html)

**Comment by nico75005** [comment]
Ok thank you.
