### ISSUE TITLE
Under swift, do I need to import the security framework manually to use the keychain?

### ISSUE THREAD

**Issue by JayJayDF** [auth0/SimpleKeychain#30]
Hello there,
I'm using the KeychainWrapper in my project and everything works fine but now I wonder about the need for the security framework which I didn't import manually. Is this something I still need to do in swift? I can Cmd+click those kSec keys in the wrapper and it sends me to the security framework - does this mean it's "built in" into swift now or something like that?

If I do need that framework why does it work right now "without" it? Are my strings saved but not encrypted or something like that?

Btw: I asked that on SO as well but the answers weren't completely satisfying thats why I ask here now.

Thanks a lot in advance

**Comment by samrat-shekhar** [comment]
this might be helpful:
[What is the difference between “import” of framework and “linking” with framework?](http://stackoverflow.com/a/29457289/5169461)
