### ISSUE TITLE
stringForKey always returns null on iOS8

### ISSUE THREAD

**Issue by jdart** [auth0/SimpleKeychain#32]
I'm using a cordova plugin that leverages this project and I'm encountering an issue where stringForKey always returns null, I've experienced this on iOS 8 and there is a report of it happening on iOS 9.2, but it seems ok on iOS 9.3. I'm also seeing an exception on a iOS 9.2 device (as a bonus issue). Any chance I could get your input?

https://github.com/driftyco/cordova-plugin-ios-keychain/issues/10
https://github.com/driftyco/cordova-plugin-ios-keychain/issues/9

**Comment by hzalaz** [comment]
Please check https://github.com/auth0/SimpleKeychain/issues/34#issuecomment-247598802.
