### ISSUE TITLE
Cannot set/fetch to Keychain using Xcode 8.0 (8A218a), Swift 3 and the iPhone simulator.

### ISSUE THREAD

**Issue by ccabanero** [auth0/SimpleKeychain#35]
Cannot set/fetch to Keychain using Xcode 8.0 (8A218a), Swift 3 and the iPhone simulator.

**Comment by hzalaz** [comment]
Please check this comment https://github.com/auth0/SimpleKeychain/issues/34#issuecomment-247598802. Not sure why Apple requires this now but seems to fix the issues

**Comment by hzalaz** [comment]
Closing this for now please reopen if the issue persists
