### ISSUE TITLE
User Presence Missing SecAccessControl options

### ISSUE THREAD

**Issue by ejohn20** [auth0/SimpleKeychain#40]
Currently the .useAccessControl property sets the kSecAccessControlUserPresence access control option.

There are stronger options that are not currently supported:

kSecAccessControlTouchIDCurrentSet
kSecAccessControlTouchIDAny

The full list can be found here: https://developer.apple.com/reference/security/secaccesscontrolcreateflags?language=objc

**Comment by marcshilling** [comment]
I could submit a pull request that adds these. The new access control options are only available on iOS 9.0, so I suppose we could check for that and fallback to `kSecAccessControlUserPresence`?

**Comment by cocojoe** [comment]
If you want to submit a PR please do.
