### ISSUE TITLE
Problem setting custom prompt message when app asks for Touch ID/Passcode

### ISSUE THREAD

**Issue by marcelogoto** [auth0/SimpleKeychain#44]
Hi,

I'm having trouble trying to set a custom prompt message when accessing Keychain.

I followed the documentation and set a new `NSString` with my custom message:

`NSString *message = NSLocalizedString(@"msg.keychain.prompt", nil);`
`NSString *savedValue = [keychain stringForKey:@"value" promptMessage:message];`

The problem is: The message doesn't show up. I tried to debug to see if I can find the problem and when the code reaches the method `- (NSDictionary *)queryFetchOneByKey:(NSString *)key message:(NSString *)message {` everything is nil, including `message`. Therefore the message isn't displayed.

<img width="691" alt="screen shot 2017-05-24 at 10 29 16 am" src="https://cloud.githubusercontent.com/assets/10403204/26405521/f3750854-406b-11e7-885d-7e789d10316d.png">
<img width="292" alt="screen shot 2017-05-24 at 10 29 31 am" src="https://cloud.githubusercontent.com/assets/10403204/26405522/f38af038-406b-11e7-9b24-73c43606bddb.png">

I'm running pod version `0.7.0`.

Any help is appreciated. Thanks!

**Comment by cocojoe** [comment]
If the message is nil, you can't expect anything to be displayed in the touch prompt. This is not a SimpleKeyChain issue, reflect upon your usage of `NSLocalizedString`

http://nshipster.com/nslocalizedstring/

**Comment by marcelogoto** [comment]
@cocojoe I guess the string isn't the problem. The `message` attribute exists until I call the `queryFetchOneByKey` method. After that it simply becomes `nil`. This might be due optimization when debugging...I tried also without NSLocalizedString and got the same result.

**Comment by marcelogoto** [comment]
Found the problem. It was the `self.useAccessControl` that was `NO`. The `nil` values were, confirmed, due to debug optimization.

My bad.
