### ISSUE TITLE
Carthage - "dyld: Library not loaded"

### ISSUE THREAD

**Issue by joerland2** [auth0/SimpleKeychain#55]
I have attempted to install SimpleKeychain via Carthage via the following steps:

1.  Add "github "auth0/SimpleKeychain"
" to Cartfile
2. Run "Carthage update"
3.  Link build phases Carthage to directory "$(SRCROOT)/Carthage/Build/iOS/SimpleKeychain.framework"

When I try to build the project in Xcode I receive the following compiler error:

dyld: Library not loaded: @rpath/SimpleKeychain.framework/SimpleKeychain
  Referenced from: /Users/<Username>/Library/Developer/Xcode/DerivedData/<Project-name>/Build/Products/Debug-iphonesimulator/Login.framework/Login
  Reason: image not found

Has anyone found a way around this and installing Simple Keychain via Carthage?

**Comment by cocojoe** [comment]
I would suggest you triple check you went through all of the carthage installation steps.
https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

Sounds like you have not added the copy frameworks step.

**Comment by joerland2** [comment]
for a full solution the following was needed:

Is there the Embed Frameworks build phase? If there isn't, you should add a new "Copy Files Phase", then select "Framrworks" for Destination, add frameworks to the list, and check "Code Sign On Copy" checkboxes.
