### ISSUE TITLE
tvOS 12: Sharing values with Access Group doesn't work

### ISSUE THREAD

**Issue by VladimirHorky86** [auth0/SimpleKeychain#58]
Hi, I am trying to share access token to topShelf extension on tvOS, but I always get a *nil* values.
Sharing is not supported on tvOS or Am I doing anything wrong?
App: 
`let keychain = A0SimpleKeychain(service: Auth0Key.SERVICE.rawValue, accessGroup: Auth0Key.GROUP.rawValue)`

`keychain.setString("pokus",` forKey: "pokus")`

topShelf:
`let keychain = A0SimpleKeychain(service: Auth0Key.SERVICE.rawValue, accessGroup: Auth0Key.GROUP.rawValue)`

`let value = keychain.string(forKey: "pokus")`

**Comment by cocojoe** [comment]
According to Apple keychain sharing is available in tvOS
https://help.apple.com/developer-account/#/dev1dcf85688

Although in this case you want to share with an `extension`. There are a lot of unknowns here, for example the configuration of sharing in Xcode etc

I would suggest here testing with 2 tvOS Apps first to confirm everything works first.

**Comment by VladimirHorky86** [comment]
Thanks for the answer. I tried it with 2 apps and it was working so after that I found I had incorrect settings of the project.
So everything is working as expected.

**Comment by cocojoe** [comment]
Glad you got it working 👍
