### ISSUE TITLE
Keychain data getting lost on app upgrade

### ISSUE THREAD

**Issue by namitgupta15** [auth0/SimpleKeychain#70]
### Description

I am storing JWT token in keychain using -

`A0SimpleKeychain().setString(token, forKey:"user-jwt")`

And using the following to retrieve it back - 

`A0SimpleKeychain().string(forKey: key)`

I am seeing in production logs that for some users, token is not getting fetched from keychain after app upgrade. Is it iOS issue or anything I am missing out here. Please suggest.

### Environment

- Version of SimpleKeychain used: 0.9.0
- Version of OS used: 12.4
- Additional dependencies that might be relevant:
- If using Carthage or CocoaPods, please include your Cartfile or Podfile
[Podfile.txt](https://github.com/auth0/SimpleKeychain/files/3511964/Podfile.txt)
- Xcode version:  10.3

**Comment by cocojoe** [comment]
This library is an ease of use wrapper over keychain functionality, so it should not impact how keychain itself functions.
