### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by lvnkmn** [auth0/SimpleKeychain#71]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

[ x ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[ x ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

[ x ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[ x ] I have checked for related or duplicate [Issues](https://github.com/auth0/SimpleKeychain/issues) and [PRs](https://github.com/auth0/SimpleKeychain/pulls).

### Environment

Please provide the following:

- Version of SimpleKeychain used: 0.9.0
- Version of OS used: iOS 13
- Additional dependencies that might be relevant:
- If using Carthage or CocoaPods, please include your Cartfile or Podfile
- Xcode version: 11

### Reproduction

- this is not a bug, just a feature request

### Feature request

Support for Swift package manager would be great, since Xcode now treats Swift Packages as a first class citizen.

**Comment by eaceto** [comment]
SimpleKeychain is an ObjC project. I think adding SPM would need first a Objective-C bridging header. And I really don't know if that is possible up to now (or the entire SimpleKeychain should be migrated to Swift first). 

If, using ObjC is possible, then adding SPM should be as simple as adding a Package.swift file with

```
import PackageDescription

let package = Package(name: "SimpleKeychain",
                      platforms: [.macOS(.v10_11),
                                  .iOS(.v9),
                                  .tvOS(.v9),
                                  .watchOS(.v2)],
                      products: [.library(name: "SimpleKeychain",
                                          targets: ["SimpleKeychain"])],
                      targets: [.target(name: "SimpleKeychain",
                                        path: "SimpleKeychain")])
```

**Comment by Widcket** [comment]
Closed by https://github.com/auth0/SimpleKeychain/pull/75.
