### ISSUE TITLE
Local Authentication is not reused

### ISSUE THREAD

**Issue by eaceto** [auth0/SimpleKeychain#73]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> When keychain's accesibility is configured as *afterFirstUnlockThisDeviceOnly* and *useAccessControl* is true, the device prompts the unlock password, once per access to keychain (either it's for setting or getting a key's value).

As specified at https://developer.apple.com/documentation/localauthentication/accessing_keychain_items_with_face_id_or_touch_id the keychain default's behavior is to create a new LocalAuthentication every time it's used. A LocalAuthentication context must be created and reuse in order to avoid this behavior (which leads to poor UX)

### Reproduction

```
keychain = A0SimpleKeychain()
keychain.useAccessControl = true
keychain.defaultAccessiblity = .afterFirstUnlockThisDeviceOnly

keychain.setString("TEST 1", forKey: "KEY 1", promptMessage: "Write KEY 1")
keychain.setString("TEST 2", forKey: "KEY 2", promptMessage: "Write KEY 2")
keychain.setString("TEST 3", forKey: "KEY 3", promptMessage: "Write KEY 3")

let v1 = keychain.string(forKey: "KEY 1", promptMessage: "Read KEY 1")
let v2 = keychain.string(forKey: "KEY 2", promptMessage: "Read KEY 2")
let v3 = keychain.string(forKey: "KEY 3", promptMessage: "Read KEY 3")

```

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:** 0.9.0
- **Version of the platform or framework used, if applicable:** iOS 13.1
- **Other relevant versions (language, server software, OS, browser):** Swift 5
- **Other modules/plugins/libraries that might be involved:**

**Comment by Widcket** [comment]
Fixed in https://github.com/auth0/SimpleKeychain/pull/74. Thanks for your contribution!

**Comment by eaceto** [comment]
Thanks to you and all the team for taking the time to review this issue and PR.
