### ISSUE TITLE
Missing nullable annotation for method keyRefOfRSAKeyWithTag:

### ISSUE THREAD

**Issue by ghennecke** [auth0/SimpleKeychain#85]
### Description

The method `- (SecKeyRef)keyRefOfRSAKeyWithTag:(NSString *)keyTag;` in the class extension `A0SimpleKeychain (KeyPair)` can return NULL but has no nullable annotation.

### Reproduction

Choose Analyze from the Product menu in Xcode for any project with the Simplekeychain Library:

`Pods/SimpleKeychain/SimpleKeychain/A0SimpleKeychain+KeyPair.m:120:9: warning: Null returned from a method that is expected to return a non-null value
        return NULL;
        ^~~~~~~~~~~
`

### Environment

- SimpleKeychain (0.10.0)
- Target platform iOS 10

**Comment by Widcket** [comment]
@ghennecke thanks for bringing this up!
